# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - learnblazor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build --filter "Category!=Integration"

      - name: dotnet publish
        run: dotnet publish learnwasm -c Release -o ./myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A4995C6EA61540F48DCBC9AC26BC491B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8B21B38858754ADEB3B4F7C2E77A734F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D51652B607CE496498163A789E4CEF09 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'learnblazor'
          slot-name: 'Production'
          package: ./myapp
          